// Code generated by sqlc. DO NOT EDIT.
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
          account_id, 
          amount
) VALUES (
  $1, $2
)
RETURNING code, account_id, amount, created_at
`

type CreateEntryParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AccountID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.Code,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
