// Code generated by sqlc. DO NOT EDIT.
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
          account_id, 
          amount
) VALUES (
  $1, $2
)
RETURNING code, account_id, amount, created_at
`

type CreateEntryParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AccountID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.Code,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE code = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, code int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, code)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT code, account_id, amount, created_at FROM entries
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, code int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, code)
	var i Entry
	err := row.Scan(
		&i.Code,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT code, account_id, amount, created_at FROM entries
ORDER BY code
LIMIT $1
OFFSET $2
`

type ListEntriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.Code,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE  entries 
SET amount = $2
WHERE code = $1
RETURNING code, account_id, amount, created_at
`

type UpdateEntryParams struct {
	Code   int64 `json:"code"`
	Amount int64 `json:"amount"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry, arg.Code, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.Code,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
