// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	Code      int64         `json:"code"`
	AccountID sql.NullInt64 `json:"account_id"`
	// this can be negative or positive
	Ammount   int64     `json:"ammount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64         `json:"id"`
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	// this must be a positive number
	Ammount   int64     `json:"ammount"`
	CreatedAt time.Time `json:"created_at"`
}
